# Generated by Django 5.1.7 on 2025-10-08 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MathCraft_Game", "0002_gamemode_delete_gameattempt"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameQuestionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_number", models.PositiveIntegerField()),
                ("question_img", models.URLField(max_length=500)),
                (
                    "time",
                    models.PositiveIntegerField(
                        help_text="Time in seconds for this question"
                    ),
                ),
                ("streak", models.PositiveIntegerField(default=0)),
                ("user_answer", models.CharField(max_length=255)),
                ("correct_answer", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("correct", "Correct"),
                            ("incorrect", "Incorrect"),
                            ("skipped", "Skipped"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "iq",
                    models.FloatField(
                        blank=True,
                        help_text="Optional IQ score for this attempt (calculated per round)",
                        null=True,
                    ),
                ),
                (
                    "game_mode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="MathCraft_Game.gamemode",
                    ),
                ),
            ],
            options={
                "ordering": ["question_number"],
                "unique_together": {("game_mode", "question_number")},
            },
        ),
    ]
