# Generated by Django 5.1.7 on 2025-10-08 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MathCraft_Game", "0003_gamequestionrecord"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gamequestionrecord",
            name="question_img",
        ),
    ]
