# Generated by Django 5.1.7 on 2025-10-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MathCraft_Game", "0004_remove_gamequestionrecord_question_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamequestionrecord",
            name="correct_answer",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="gamequestionrecord",
            name="question_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="gamequestionrecord",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("correct", "Correct"),
                    ("incorrect", "Incorrect"),
                    ("skipped", "Skipped"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="gamequestionrecord",
            name="time",
            field=models.PositiveIntegerField(
                blank=True, help_text="Time in seconds for this question", null=True
            ),
        ),
        migrations.AlterField(
            model_name="gamequestionrecord",
            name="user_answer",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
