# Generated by Django 5.1.7 on 2025-10-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MathCraft_Game", "0005_alter_gamequestionrecord_correct_answer_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gamequestionrecord",
            name="iq",
        ),
        migrations.AddField(
            model_name="gamemode",
            name="iq",
            field=models.FloatField(
                blank=True, help_text="Overall IQ for this attempt", null=True
            ),
        ),
    ]
