# Generated by Django 5.1.7 on 2025-10-12 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MathCraft_Game", "0010_cointransaction"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CoinTransaction",
        ),
    ]
